services/billing_admin/billing/apps/subscriptions/api/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Billing API",
        default_version='v1',
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('v1/', include('billing.apps.subscriptions.api.v1.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

services/billing_admin/billing/apps/subscriptions/api/v1/urls.py
from django.urls import path

from .views import (
    TariffDetailApi, UserSubscriptionsApi, ProductListApi,
    PaymentAPIView, UserSubscriptionDetailApi, UserUnsubscribeApi
)

urlpatterns = [
    path('products/', ProductListApi.as_view()),
    path('tariff/<uuid:tariff_id>', TariffDetailApi.as_view()),
    path('order/', PaymentAPIView.as_view()),
    path('subscriptions/', UserSubscriptionsApi.as_view()),
    path('subscriptions/<uuid:subscription_id>', UserSubscriptionDetailApi.as_view()),
    path('subscriptions/<uuid:subscription_id>/unsubscribe', UserUnsubscribeApi.as_view()),
]

services/billing_admin/demo/urls.py
from django.urls import path

from demo.views import login, profile, movies, logout, index, movies_detail, tariff, order, subscribe, \
    subscriptions, products,unsubscribe

app_name = "demo"

urlpatterns = [
    path('', index, name='login'),
    path('login/', login, name='login'),
    path('profile/', profile, name='profile'),
    path('movies/', movies, name='movies'),
    path('movies/<str:movies_id>', movies_detail, name='movies_detail'),
    path('products/', products, name='products'),
    path('tariff/<str:tariff_id>', tariff, name='tariff'),
    path('order/', order, name='order'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('subscriptions/<str:subscribe_id>', subscribe, name='subscribe'),
    path('subscriptions/<str:subscribe_id>/unsubscribe', unsubscribe, name='unsubscribe'),
    path('logout/', logout, name='logout'),
]

services/billing_admin/billing/apps/subscriptions/models/audit.py
import logging

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.forms.models import model_to_dict
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel

from billing.apps.subscriptions.tasks import audit_create_task

logger = logging.getLogger(__name__)


class AuditMixin(models.Model):
    class Meta:
        abstract = True

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, action=None):
        super().save(force_insert, force_update, using, update_fields)
        status = action or getattr(self, 'status', 'something')
        AuditEvents.create('models', status, self, self.details)

    @property
    def details(self) -> str:
        return str(model_to_dict(self))


class AuditEvents(TimeStampedModel):
    """История событий."""
    who = models.CharField(_("Инициатор события"), max_length=50)
    what = models.CharField(_("Событие"), max_length=50)
    details = models.TextField(_("Подробности"), blank=True, null=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, default=None, null=True, blank=True)
    object_id = models.CharField(max_length=100, default=None, null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = _('событие')
        verbose_name_plural = _('события')

    @classmethod
    def create(cls, who, what, instance, details=None) -> None:
        audit_create_task.apply_async(
            args=(who, what, instance._meta.app_label, instance._meta.object_name, instance.id, details)
        )

services/billing_admin/billing/apps/subscriptions/models/meta.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class AccessType(models.TextChoices):
    FREE = 'free', _('бесплатный доступ')
    STANDARD = 'standard', _('обычная подписка')
    EXTRA = 'extra', _('расширенная подписка')


class PaymentSystem(models.TextChoices):
    """Платежные системы, например YooKassa, robokassa, и т.д."""
    YOOMONEY = settings.YOOMONEY, _("Платежная система Юмани")
    STRIPE = settings.STRIPE, _("Платежная система Stripe")


class SubscriptionPeriods(models.TextChoices):
    """Периоды списания средств."""
    MONTHLY = "per month", _("каждый месяц")
    YEARLY = "per year", _("каждый год")


class SubscriptionStatus(models.TextChoices):
    """Статусы подписок."""
    DRAFT = "draft", _("На оформлении")
    INACTIVE = "inactive", _("Не активная")
    ACTIVE = "active", _("Активная")
    EXPIRED = "expired", _("Истек срок действия")
    CANCELLED = "cancelled", _("Подписка отменена")
    CANCEL_AT_PERIOD_END = "cancel_at_period_end", _("Отмена после окончания периода")

    @classmethod
    @property
    def active_statuses(cls):
        return [cls.ACTIVE, cls.CANCEL_AT_PERIOD_END]


class PaymentStatus(models.TextChoices):
    """Статусы платежей."""
    NOT_PAYED = "not_payed", _("Не оплачен")
    PAYED = "payed", _("Оплачен")
    PENDING = "pending", _("Ждем подтверждения оплаты")
    FAILED = "failed", _("Оплата не успешна")
    CANCELLED = "cancelled", _("Оплата отменена")
    REFUNDED = "refunded", _("Выполнен возврат")

services/billing_admin/billing/apps/subscriptions/payment_system/models.py
from enum import Enum


class SubscribePaymentStatus(Enum):
    """Статусы подписки, возвращаемые из платежной системы."""
    ACTIVE = "active"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


class PaymentStatus(Enum):
    """Статусы платежей, возвращаемые из платежной системы."""
    PAID = "paid"
    UNPAID = "unpaid"
    CANCELED = "canceled"

services/billing_admin/demo/forms.py
from django import forms
from requests import HTTPError

from demo.services import auth_login


class LoginForm(forms.Form):
    login = forms.CharField(label='Login', max_length=100)
    password = forms.CharField(label='Password', max_length=100)
    access_token = None
    refresh_token = None

    def is_valid(self):
        is_valid = super().is_valid()
        if not is_valid:
            return False
        try:
            data = auth_login(self.cleaned_data['login'], self.cleaned_data['password'])
        except HTTPError as e:
            self.errors.update({'auth': str(e)})
            return False

        self.access_token = data['access_token']
        self.refresh_token = data['refresh_token']

        return True

services/billing_admin/billing/apps/subscriptions/api/v1/views/payment.py
import logging

from drf_yasg import openapi
from drf_yasg.openapi import Schema
from drf_yasg.utils import swagger_auto_schema
from rest_framework.response import Response
from rest_framework.views import APIView

from billing.apps.subscriptions.api.v1.serializers import PaymentSerializer
from billing.apps.subscriptions.services.subscription import subscription_create

logger = logging.getLogger(__file__)


class PaymentAPIView(APIView):
    """Представление для запуска оплаты подписки."""
    http_method_names = ['post', ]

    @swagger_auto_schema(
        request_body=PaymentSerializer,
        responses={
            200: openapi.Response(
                'Success', Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'confirmation_url':
                            Schema(type=openapi.TYPE_STRING)
                    }
                )
            ),
            400: openapi.Response('Bad request')
        }
    )
    def post(self, request):
        serializer = PaymentSerializer(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data
        user_id = request.scope['user_id']
        payment_system = data['payment_system']
        tariff_id = data['tariff_id']
        subscription = subscription_create(user_id, tariff_id, payment_system)
        url = subscription.process_confirm()
        return Response({'confirmation_url': url})

services/billing_admin/billing/apps/subscriptions/api/v1/views/product.py
import logging

from rest_framework import generics

from billing.apps.subscriptions.api.v1.serializers import ProductSerializer
from billing.apps.subscriptions.models import Product

logger = logging.getLogger(__file__)


class ProductListApi(generics.ListAPIView):
    http_method_names = ['get', ]
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

services/billing_admin/billing/apps/subscriptions/api/v1/views/subscriptions.py
import logging

from django.http import Http404
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.views import APIView

from billing.apps.subscriptions.api.v1.serializers import SubscriptionSerializer
from billing.apps.subscriptions.models import Subscription, AuditEvents
from billing.apps.subscriptions.tasks import unsubscribe_task

logger = logging.getLogger(__file__)


class FilterByUserMixin:
    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.scope.get('user_id')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = self.queryset
        qs = qs.filter_by_user_id(self.user_id)
        return qs


class UserSubscriptionsApi(FilterByUserMixin, generics.ListAPIView):
    """Список подписок пользователя."""
    http_method_names = ['get', ]
    queryset = Subscription.objects.all()
    serializer_class = SubscriptionSerializer

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.exclude_cancelled()
        return qs


class UserSubscriptionDetailApi(FilterByUserMixin, generics.RetrieveAPIView):
    """Детальная информация о подписке."""
    http_method_names = ['get', ]
    queryset = Subscription.objects.all()
    serializer_class = SubscriptionSerializer

    def get_object(self):
        qs = super().get_queryset()
        return qs.filter(pk=self.kwargs['subscription_id']).first()


class UserUnsubscribeApi(FilterByUserMixin, APIView):
    """Отписка."""

    http_method_names = ['get']
    queryset = Subscription.objects.all()

    def get_object(self):
        qs = super().get_queryset()
        return qs.filter(pk=self.kwargs['subscription_id']).first()

    def get(self, request, *args, **kwargs):
        subscription = self.get_object()
        if not subscription:
            return Http404()

        unsubscribe_task.apply_async((subscription.id,))
        AuditEvents.create(f"user {self.user_id}", 'unsubscribe', subscription)
        return Response({'status': 'ok'})

services/billing_admin/billing/apps/subscriptions/api/v1/views/tariffs.py
import logging

from rest_framework import generics

from billing.apps.subscriptions.api.v1.serializers import TariffDetailSerializer
from billing.apps.subscriptions.models import Tariff

logger = logging.getLogger(__file__)


class TariffDetailApi(generics.RetrieveAPIView):
    lookup_url_kwarg = 'tariff_id'
    http_method_names = ['get', ]
    queryset = Tariff.objects.all()
    serializer_class = TariffDetailSerializer

services/billing_admin/demo/views.py
from functools import wraps

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from requests import RequestException
from demo.forms import LoginForm
from demo.services import (
    auth_profile, auth_logout, async_movies_search, async_movies_detail,
    billing_tariff, billing_order, billing_subscribe, auth_access_check,
    billing_subscriptions, billing_products, billing_unsubscribe, auth_refresh
)


def index(request):
    access_token = request.session.get('access_token', '')
    if not access_token:
        return HttpResponseRedirect(reverse('demo:login'))
    return HttpResponseRedirect(reverse('demo:profile'))


def check_token(view_func):
    """Проверка валидности токена."""

    def wrapped_view(request, **kwargs):
        access_token = request.session.get('access_token')
        refresh_token = request.session.get('refresh_token')

        if not access_token or not refresh_token:
            return HttpResponseRedirect(reverse('demo:login'))

        if not auth_access_check(access_token):
            try:
                tokens = auth_refresh(refresh_token)
            except:
                request.session['access_token'] = None
                request.session['refresh_token'] = None
                return HttpResponseRedirect(reverse('demo:login'))

            request.session['access_token'] = tokens['access_token']
            request.session['refresh_token'] = tokens['refresh_token']

        return view_func(request, **kwargs)

    return wraps(view_func)(wrapped_view)


def login(request):
    """Логин."""
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            request.session['access_token'] = form.access_token
            request.session['refresh_token'] = form.refresh_token
            return HttpResponseRedirect(reverse('demo:profile'))
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


@check_token
def profile(request):
    """Профиль пользователя."""

    access_token = request.session.get('access_token')
    if not access_token:
        return HttpResponseRedirect(reverse('demo:login'))

    ctx = {}
    try:
        ctx = auth_profile(access_token)
    except RequestException as e:
        ctx['errors'] = str(e)

    ctx['access_token'] = access_token
    ctx['refresh_token'] = request.session.get('refresh_token')

    return render(request, 'profile.html', ctx)


def logout(request):
    """Выход пользователя."""
    access_token = request.session.get('access_token', '')

    if access_token:
        request.session['access_token'] = None
        request.session['refresh_token'] = None

    auth_logout(access_token)

    return HttpResponseRedirect(reverse('demo:login'))


@check_token
def movies(request):
    """Доступные фильмы."""
    access_token = request.session.get('access_token')
    ctx = {'data': [], 'query': ''}

    if request.method == 'POST':
        query = request.POST['query']
        ctx['query'] = query

        try:
            ctx['data'] = async_movies_search(access_token, query)
        except RequestException as e:
            ctx['errors'] = str(e)

    return render(request, 'movies.html', ctx)


@check_token
def movies_detail(request, movies_id):
    """Информация о фильме."""
    access_token = request.session.get('access_token')
    ctx = {'data': []}

    try:
        ctx['data'] = async_movies_detail(access_token, movies_id)
    except RequestException as e:
        ctx['errors'] = str(e)

    return render(request, 'movies_detail.html', ctx)


@check_token
def products(request):
    """Продукты."""
    access_token = request.session.get('access_token')
    ctx = {'data': []}

    try:
        ctx['data'] = billing_products(access_token)
    except RequestException as e:
        ctx['errors'] = str(e)

    return render(request, 'products.html', ctx)


@check_token
def tariff(request, tariff_id):
    """Оформить подписку."""
    access_token = request.session.get('access_token')
    ctx = {'data': []}

    try:
        ctx['data'] = billing_tariff(access_token, tariff_id)
    except RequestException as e:
        ctx['errors'] = str(e)

    return render(request, 'tariff.html', ctx)


@check_token
def order(request):
    """Оплата подписки."""
    if not request.POST:
        return render(request, '500.html', {'errors': 'Something went wrong'})

    tariff_id = request.POST.get('tariff_id')
    payment_system = request.POST.get('payment_system')
    access_token = request.session.get('access_token')
    ctx = {'data': []}

    try:
        ctx['data'] = billing_order(access_token, tariff_id, payment_system)
    except RequestException as e:
        ctx['errors'] = str(e)
        return render(request, '500.html', ctx)

    return HttpResponseRedirect(ctx['data']['confirmation_url'])  # noqa


@check_token
def subscriptions(request):
    """Мои подписки."""

    access_token = request.session.get('access_token')
    ctx = {'data': []}

    try:
        ctx['data'] = billing_subscriptions(access_token)
    except RequestException as e:
        ctx['errors'] = str(e)
        return render(request, '500.html', ctx)

    return render(request, 'subscriptions.html', ctx)


@check_token
def subscribe(request, subscribe_id):
    """Статус подписки."""

    refresh_page = request.GET.get('refresh_page', "0")
    access_token = request.session.get('access_token')
    ctx = {
        'data': [],
        'refresh_page': refresh_page
    }

    try:
        ctx['data'] = billing_subscribe(access_token, subscribe_id)
    except RequestException as e:
        ctx['errors'] = str(e)
        return render(request, '500.html', ctx)

    return render(request, 'subscribe.html', ctx)


@check_token
def unsubscribe(request, subscribe_id):
    """Отмена подписки."""

    access_token = request.session.get('access_token')

    try:
        billing_unsubscribe(access_token, subscribe_id)
    except RequestException as e:
        ctx = {'errors': str(e)}
        return render(request, '500.html', ctx)

    return HttpResponseRedirect(reverse('demo:subscribe', args=(subscribe_id,)) + "?refresh_page=1")

services/billing_admin/demo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block extrahead %}
    {% endblock %}
</head>

<body>
{% include 'header.html' %}
<main class="flex-shrink-0">
    <div class="container mt-5">
        {% block body %}
        {% endblock %}
    </div>
</main>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>

services/billing_admin/demo/templates/header.html
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    main > .container {
        padding: 60px 15px 0;
    }
</style>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">Movies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'demo:profile' %}">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'demo:subscriptions' %}">Мои подписки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'demo:movies' %}">Поиск фильмов</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'demo:products' %}">Продукты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'demo:logout' %}" tabindex="-1">Выход</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

services/billing_admin/demo/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body class="text-center">
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    html,
    body {
        height: 100%;
    }

    body {
        display: flex;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    .form-signin .checkbox {
        font-weight: 400;
    }

    .form-signin .form-floating:focus-within {
        z-index: 2;
    }

    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }

</style>
<main class="form-signin">
    <form action="{% url 'demo:login' %}" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating">
            <input type="email" class="form-control" id="id_login" name="login" placeholder="name@example.com">
            <label for="id_login">Email address</label>
        </div>
        <div class="form-floating">
            <input id="id_password" name="password" type="password" class="form-control" placeholder="Password">
            <label for="id_password">Password</label>
        </div>


        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    </form>
</main>

</body>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</html>

services/billing_admin/demo/templates/movies.html
{% extends 'base.html' %}
{% block title %} Поиск фильмов {% endblock %}
{% block body %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="moviesPart" id="movies">
            <div class="mb-3 input-group">
                <input class="form-control" type="text" placeholder="Введите название фильма..." id="id_query"
                       name="query"
                       value="{{ query }}"/>
                <button type="submit" class="btn btn-primary">Поиск</button>
            </div>

        </div>
    </form>
    {% if data %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                <th scope="col">Rating</th>
                <th scope="col">Access</th>
            </tr>
            </thead>
            <tbody>
            {% for movie in data %}
                <tr>
                    <th scope="row"><a href="{% url 'demo:movies_detail' movie.id %}"> {{ movie.id }}</a></th>
                    <td>{{ movie.title }}</td>
                    <td>{{ movie.imdb_rating }}</td>
                    <td>{{ movie.access_type }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% if errors %}
        {{ errors }}
    {% endif %}
{% endblock %}

services/billing_admin/demo/templates/products.html
{% extends 'base.html' %}
{% block title %} Продукты {% endblock %}
{% block body %}
    <style>
        table {
            width: 100%;
        }

        table tr {
            height: 42px;
            margin: 5px;
        }
    </style>
    {% if data %}
        <h2 class="pb-2 border-bottom">Подписки</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-4">
            {% for product in data.results %}
                <div class="card m-3" style="width: 20rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ product.description }}</h6>
                        <div class="row mt-5">
                        {% for fariff in product.tariffs %}
                            <div class="block" style="width: 50%;">
                            {% if fariff.period == "per year" %}Год{% else %}Месяц{% endif %}
                            <p>{{ fariff.price }} руб.</p>
                            <p style="width:120px">
                                {% if fariff.discount.value %}Скидка: {{ fariff.discount.value }} %{% else %}&nbsp;{% endif %}
                            </p>
                            <a class="btn btn-primary" href="{% url "demo:tariff" fariff.id %}">Оформить</a>
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% if errors %}
        {{ errors }}
    {% endif %}
{% endblock %}

services/billing_admin/demo/templates/subscribe.html
{% extends 'base.html' %}
{% block title %} Статус подписки {% endblock %}
{% block extrahead %}
    {% if refresh_page == "1" and data.id %}
        <meta http-equiv="refresh"
              content="3; url={% url 'demo:subscribe' data.id %}?refresh_page={{ refresh_page }}">
    {% endif %}
{% endblock %}
{% block body %}
    <h1>{{ data.tariff.product.name }}</h1>
    <p class="fs-5 col-md-8">{{ data.tariff.product.description }}</p>
    <p class="fs-5 col-md-8"><strong>Цена: </strong>{{ data.tariff.price }}</p>
    <p class="fs-5 col-md-8"><strong>Период: </strong>{% if data.period == "per year" %}Год{% else %}Месяц{% endif %}
    </p>
    <p class="fs-5 col-md-8"><strong>Дата окончания: </strong>{{ data.expiration_date }}</p>

    {% if data.discount_name %}
        <p class="fs-5 col-md-8"><strong>Скидка: </strong>{{ data.discount.name }} {{ data.discount.value }}%</p>
    {% endif %}
    </p>
    <p class="fs-5 col-md-8 {% if data.status == 'active' %} text-success {% else %} text-danger {% endif %}">
        <strong>Статус: </strong>{{ data.status_display }}
    </p>
    {% if data.status == 'active' %} <a class="btn btn-danger" href="{% url "demo:unsubscribe" data.id %}">Отменить</a>
    {% endif %}


    {% if errors %}
        {{ errors }}
    {% endif %}
{% endblock %}

services/billing_admin/demo/templates/tariff.html
{% extends 'base.html' %}
{% block title %} Подписки {% endblock %}
{% block body %}
    <h1>{{ data.product.name }}</h1>
    <p class="fs-5 col-md-8">{{ data.product.description }}</p>
    <p class="fs-5 col-md-8"><strong>ID: </strong>{{ data.id }}</p>
    <p class="fs-5 col-md-8"><strong>Цена: </strong>{{ data.price }}</p>
    <p class="fs-5 col-md-8"><strong>Период: </strong>{% if data.period == "per year" %}Год{% else %}Месяц{% endif %}
    </p>
    {% if data.discount.name %}
        <p class="fs-5 col-md-8"><strong>Скидка: </strong>{{ data.discount.name }} {{ data.discount.value }}%</p>
    {% endif %}

    {% if errors %}
        {{ errors }}
    {% endif %}
    <form action="{% url 'demo:order' %}" method="POST" class="form-inline">
        {% csrf_token %}
        <input type="hidden" name="tariff_id" value={{ data.id }}>
        <div class="row">
            <label class="col-form-label col-auto fs-5"><strong>Платежная система:</strong></label>
            <div class="col-auto">
                <select class="form-select my-1" name="payment_system">
                    <option value="yoomoney" selected>Юмани</option>
                    <option value="stripe">Stripe</option>
                </select>
            </div>
            <div class="col-auto">
                <button class="btn btn-primary my-1" type="submit">Купить</button>
            </div>
        </div>

    </form>
{% endblock %}